config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'technologies#index'
  get '/', to: 'technologies#index'
  get '/new', to: 'repositories#new'
  post '/new', to: 'repositories#create'
  get ':technology', to: 'technologies#show', as: 'technology'
  get ':technology/:category', to: 'categories#show', as: 'category'
  get ':technology/:category/:repository', to: 'repositories#show', as: 'repository'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/repository.rb
# frozen_string_literal: true

class Repository < ApplicationRecord
  before_validation :set_name, on: :create

  validates :full_name, presence: true, uniqueness: { case_sensitive: false }

  serialize :external_info, Hash

  def set_name
    self.name ||= full_name&.split('/')[1] || full_name
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  def show
    @technology = permitted_params[:technology]
    @category = permitted_params[:category]
    @repositories = Repository.where(technology: @technology, category: @category).pluck(:name).compact.sort
  end

  private

  def permitted_params
    params.permit(:technology, :category)
  end
end

app/controllers/repositories_controller.rb
# frozen_string_literal: true

class RepositoriesController < ApplicationController
  def new; end

  def create
    repository = Repository.new(permitted_params)

    if repository.save
      SyncRepositoryService.execute(repository)

      redirect_to repository_path(repository.technology, repository.category, repository.name)
    else
      flash[:error] = repository.errors.full_messages
      render :new
    end
  end

  def show
    @technology = permitted_params[:technology]
    @category = permitted_params[:category]
    @repository = Repository.find_by(technology: @technology,
                                     category: @category,
                                     name: permitted_params[:repository])
  end

  private

  def permitted_params
    params.permit(:technology, :category, :repository, :full_name)
  end
end

app/controllers/technologies_controller.rb
# frozen_string_literal: true

class TechnologiesController < ApplicationController
  def index
    @technologies = Repository.distinct.pluck(:technology).sort
  end

  def show
    @technology = permitted_params[:technology]
    @categories = Repository.where(technology: @technology).pluck(:category).uniq.sort
  end

  private

  def permitted_params
    params.permit(:technology)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/categories/show.html.erb
<h1><%= link_to(@technology, technology_path(@technology)) %> >> <%= @category %></h1>

<ul>
  <% @repositories.each do |repository| %>
    <li><%= link_to repository, repository_path(@technology, @category, repository) %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AwesomeGithubList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul>
      <li><%= link_to 'Home', root_path %></li>
      <li><%= link_to 'Back', :back %></li>
      <li><%= link_to 'New', new_path %></li>
    </ul>

    <%= yield %>
  </body>
</html>

app/views/repositories/new.html.erb
<%= flash[:error] %>

<%= form_with do |form| %>
  <ul>
    <li>
      <%= form.label :technology, "Technology" %>
      <%= form.text_field :technology, placeholder: 'ruby' %>
    </li>

    <li>
      <%= form.label :category, "Category" %>
      <%= form.text_field :category, placeholder: 'authentication' %>
    </li>

      <li>
      <%= form.label :full_name, "Github Repo" %>
      <%= form.text_field :full_name, placeholder: 'oauth-xx/oauth2' %>
    </li>

    <li><%= form.submit "Create" %></li>
  </ul>
<% end %>

app/views/repositories/show.html.erb
<h1><%= link_to(@technology, technology_path(@technology)) %> >> <%= link_to(@category, category_path(@technology, @category)) %> >> <%= @repository.name || @repository.full_name %></h1>

<ul>
  <li><b>Name:</b> <%= @repository.name %></li>
  <li><b>Full Name:</b> <%= @repository.full_name %></li>
  <li><b>Technology:</b> <%= @repository.technology %></li>
  <li><b>Category:</b> <%= @repository.category %></li>
  <li><b>Is a Fork:</b> <%= @repository.external_info['fork'] %></li>
  <li><b>Forks Count:</b> <%= @repository.external_info['forks_count'] %></li>
  <li><b>Stars:</b> <%= @repository.external_info['stargazers_count'] %></li>
  <li><b>Watchers:</b> <%= @repository.external_info['watchers_count'] %></li>
</ul>

app/views/technologies/index.html.erb
<h1> Technologies </h1>

<ul>
  <% @technologies.each do |technology| %>
    <li><%= link_to technology, technology_path(technology) %></li>
  <% end %>
</ul>

app/views/technologies/show.html.erb
<h1><%= @technology %></h1>

<ul>
  <% @categories.each do |category| %>
    <li><%= link_to category, category_path(@technology, category) %></li>
  <% end %>
</ul>